= 自動LaTeX組版
B̅ (cmplstofB) <20594300+cmplstofB@users.noreply.github.com>
v0.1.0, 2020-07-30

== これはなに

GitHub Actionsを利用して，
Docker上でLaTeXで組版し，
生成したPDFを上げ込むところまでを
無償で自動化した例。

一般的には中小規模の論文執筆
に向いていると思われる。
大規模の論文では，
恐らく組版頻度が少なすぎる。


== 特徴

* 可能な限り公式の道具を用い，
  また自分で書く量を少なくしている。
  既に高品質のものが用意されているのに
  車輪の再発明はしたくないし，
  自分の管轄下に複雑な環境を導入したくない。

** LaTeXが乗るDockerは
   自力では作成せず，
   https://github.com/Dockershelf[Dockershelf]
   が配布し隔日で更新しているものを利用する。

** 自動組版の開始設定や，
   生成したPDFをどのように配置するかは，
   GitHub Actionsが公式に用意している
   https://github.com/actions/upload-release-asset[構築例]
   を参考にする。
   （自分で独自命令を考えたりしない）


== しくみ

* 手許でLaTeX原稿を編集する。
例えば，
[source,console]
----
$ editor main.tex
----

* git標識を賦与する。
例えば，
[source,console]
----
$ git tag v42.0.1
----

* GitHubに押し込む。
例えば，
[source,console]
----
$ git push origin v42.0.1
----

ここでGitHub Actionsが作動。
「pushかつ “v” から始まるtagが賦与されていれば
指定した一連の動作（具体的にはLaTeX組版と
Releaseへの上げ込み）を行う」
という設定にしているので，
如述の操作に感応する。

Dockerが構築されて原稿が処理され，
しばらく待つと
Releaseが一つ増えてそこに
組版結果のPDF文書が上がる。


== やりたいこと

標識を自動で増分したい::
  これは多分そう難しくないけど，
  できればgitやGitHubの機能を用いて
  効率的・最小限の追加で達成したい。
