# This is a basic workflow that is manually triggered

name: 自動LaTeX組版

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    tags:
      - 'v*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
    name: LaTeX組版
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: dockershelf/latex:full
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: 原稿を勘定
      uses: actions/checkout@v2
    - name: latexmkによる備立
      run: |
        latexmk main.tex
    - name: 成果物として上げ込み
      uses: actions/upload-artifact@v2
      with:
        name: main.pdf
        path: ./main.pdf
  changelog:
    name: 変更履歴関連
    runs-on: ubuntu-latest
    needs: build
    outputs:
      commit_message:
    steps:
      - uses: actions/checkout@v1
      - name: commit_messageを設定
        run: |
          echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.event.after }})"
  release:
    name: 組版結果を離立
    runs-on: ubuntu-latest
    needs: changelog
    steps:
    - name: 公開版を生成
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: 公開版 (${{ github.ref }})
        body: ${{ needs.changelog.outputs.commit_message }}
        draft: false
        prerelease: false
    - name: 公開版用の成果物を下し込み
      uses: actions/download-artifact@v2
      with:
        name: main.pdf
    - name: 公開版を上げ込み
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./main.pdf
        asset_name: main.pdf
        asset_content_type: application/pdf
